#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${RED}Database Table Deletion Script${NC}"
echo "================================"
echo ""

# Check if Cargo.toml exists
if [ ! -f "Cargo.toml" ]; then
    echo -e "${RED}Error: Cargo.toml not found${NC}"
    exit 1
fi

# Extract project name from Cargo.toml (get the package name, not the binary name)
PROJECT_NAME=$(awk -F'"' '/^name =/ {print $2; exit}' Cargo.toml)
if [ -z "$PROJECT_NAME" ]; then
    echo -e "${RED}Error: Could not extract project name from Cargo.toml${NC}"
    exit 1
fi

# Convert project name to underscore format for table name
PROJECT_NAME_UNDERSCORE=$(echo "$PROJECT_NAME" | tr '-' '_')
TABLE_NAME="${PROJECT_NAME_UNDERSCORE}_table"

echo -e "${BLUE}Project name: ${PROJECT_NAME}${NC}"
echo -e "${BLUE}Table name: ${TABLE_NAME}${NC}"
echo ""

# Check if docker-compose.yml exists
if [ ! -f "docker-compose.yml" ]; then
    echo -e "${RED}Error: docker-compose.yml not found${NC}"
    exit 1
fi

# Extract database connection info from docker-compose.yml
POSTGRES_USER=$(grep -A 10 "postgres:" docker-compose.yml | grep "POSTGRES_USER:" | sed -E 's/.*POSTGRES_USER:\s*(.+)/\1/' | tr -d ' ')
POSTGRES_PASSWORD=$(grep -A 10 "postgres:" docker-compose.yml | grep "POSTGRES_PASSWORD:" | sed -E 's/.*POSTGRES_PASSWORD:\s*(.+)/\1/' | tr -d ' ')
POSTGRES_DB=$(grep -A 10 "postgres:" docker-compose.yml | grep "POSTGRES_DB:" | sed -E 's/.*POSTGRES_DB:\s*(.+)/\1/' | tr -d ' ')
CONTAINER_NAME=$(grep -A 10 "postgres:" docker-compose.yml | grep "container_name:" | sed -E 's/.*container_name:\s*(.+)/\1/' | tr -d ' ')

if [ -z "$POSTGRES_USER" ] || [ -z "$POSTGRES_PASSWORD" ] || [ -z "$POSTGRES_DB" ] || [ -z "$CONTAINER_NAME" ]; then
    echo -e "${RED}Error: Could not extract database connection info from docker-compose.yml${NC}"
    echo "Please make sure docker-compose.yml contains PostgreSQL service configuration"
    exit 1
fi

echo -e "${BLUE}Database: ${POSTGRES_DB}${NC}"
echo -e "${BLUE}User: ${POSTGRES_USER}${NC}"
echo -e "${BLUE}Container: ${CONTAINER_NAME}${NC}"
echo ""

# Check if container is running
if ! docker ps | grep -q "$CONTAINER_NAME"; then
    echo -e "${YELLOW}Warning: PostgreSQL container '$CONTAINER_NAME' is not running${NC}"
    echo "Please start it with: docker-compose up -d"
    exit 1
fi

# Check if table exists
TABLE_EXISTS=$(echo "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = '${TABLE_NAME}');" | docker exec -i "$CONTAINER_NAME" psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -t -A 2>/dev/null | tr -d ' ')

if [ "$TABLE_EXISTS" != "t" ]; then
    echo -e "${YELLOW}Table '${TABLE_NAME}' does not exist in the database.${NC}"
    echo ""
    read -p "Do you want to clean up generated code from main.rs anyway? (y/n): " CLEAN_CODE
    if [ "$CLEAN_CODE" = "y" ] || [ "$CLEAN_CODE" = "Y" ]; then
        # Clean up generated code from main.rs
        echo ""
        echo "Cleaning up generated code from main.rs..."
        
        # Backup main.rs
        cp main.rs main.rs.bak.delete
        
    if grep -q "// Generated by setup-db.sh" main.rs; then
        # Remove everything from "// Generated by setup-db.sh" to just before "async fn main" or "#[actix_web::main]"
        # Use awk to remove the generated section
        awk '
            /^\/\/ Generated by setup-db\.sh/ { skip=1; next }
            skip && (/^#\[actix_web::main\]/ || /^async fn main\(\)/) { skip=0 }
            !skip { print }
        ' main.rs > main.rs.tmp && mv main.rs.tmp main.rs
        
        # Remove CRUD routes
        sed -i.bak.delete2 "/\.route(\"\/${PROJECT_NAME_UNDERSCORE}/d" main.rs
        
        # Ensure #[actix_web::main] is before async fn main if it was removed
        if ! grep -q "#\[actix_web::main\]" main.rs && grep -q "^async fn main" main.rs; then
            awk '
                /^async fn main/ {
                    print "#[actix_web::main]"
                }
                { print }
            ' main.rs > main.rs.tmp && mv main.rs.tmp main.rs
        fi
        
        echo -e "${GREEN}✓ Generated code removed from main.rs!${NC}"
        echo -e "${YELLOW}Backup saved as main.rs.bak.delete${NC}"
    else
        echo -e "${YELLOW}No generated code found in main.rs${NC}"
    fi
        
        # Clean up backup files
        rm -f main.rs.bak.delete2
    fi
    exit 0
fi

echo -e "${YELLOW}Warning: This will permanently delete the table '${TABLE_NAME}' and all its data!${NC}"
echo ""
read -p "Are you sure you want to delete the table? (y/n): " CONFIRM

if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
    echo "Aborted."
    exit 0
fi

# Drop the table
echo ""
echo "Dropping table '${TABLE_NAME}'..."
DROP_SQL="DROP TABLE IF EXISTS ${TABLE_NAME} CASCADE;"

echo "$DROP_SQL" | docker exec -i "$CONTAINER_NAME" psql -U "$POSTGRES_USER" -d "$POSTGRES_DB"

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Table '${TABLE_NAME}' deleted successfully!${NC}"
else
    echo -e "${RED}Error: Failed to delete table${NC}"
    exit 1
fi

# Ask if user wants to clean up generated code from main.rs
echo ""
read -p "Do you want to remove the generated CRUD code from main.rs? (y/n): " CLEAN_CODE

if [ "$CLEAN_CODE" = "y" ] || [ "$CLEAN_CODE" = "Y" ]; then
    echo ""
    echo "Cleaning up generated code from main.rs..."
    
    # Backup main.rs
    cp main.rs main.rs.bak.delete
    
    # Remove generated structs and CRUD functions
    if grep -q "// Generated by setup-db.sh" main.rs; then
        # Remove everything from "// Generated by setup-db.sh" to just before "async fn main" or "#[actix_web::main]"
        awk '
            /^\/\/ Generated by setup-db\.sh/ { skip=1; next }
            skip && (/^#\[actix_web::main\]/ || /^async fn main\(\)/) { skip=0 }
            !skip { print }
        ' main.rs > main.rs.tmp && mv main.rs.tmp main.rs
        
        # Remove CRUD routes
        sed -i.bak.delete2 "/\.route(\"\/${PROJECT_NAME_UNDERSCORE}/d" main.rs
        
        # Ensure #[actix_web::main] is before async fn main if it was removed
        if ! grep -q "#\[actix_web::main\]" main.rs && grep -q "^async fn main" main.rs; then
            awk '
                /^async fn main/ {
                    print "#[actix_web::main]"
                }
                { print }
            ' main.rs > main.rs.tmp && mv main.rs.tmp main.rs
        fi
        
        echo -e "${GREEN}✓ Generated code removed from main.rs!${NC}"
        echo -e "${YELLOW}Backup saved as main.rs.bak.delete${NC}"
    else
        echo -e "${YELLOW}No generated code marker found in main.rs${NC}"
    fi
    
    # Clean up backup files
    rm -f main.rs.bak.delete2
fi

echo ""
echo -e "${GREEN}✓ Database cleanup complete!${NC}"
echo ""
echo "You can now run ./setup-db.sh to create a fresh table."

